### ISSUE TITLE
Videos are sometimes only a few KB large, and unplayable

### ISSUE THREAD

**Issue by ausafali** [thefiz/TwitchClipDownloader#1]
i am trying to download some clips but in return it just in kb file.

**Comment by thefiz** [comment]
Can you provide a sample link?

**Comment by ausafali** [comment]
https://clips.twitch.tv/TolerantIncredulousSwallowRalpherZ
https://clips.twitch.tv/RudeBraveStaplePartyTime

**Comment by ausafali** [comment]
check imgur link please
https://i.imgur.com/BnfAMTD.png

**Comment by thefiz** [comment]
Thank you for the examples.  I can troubleshoot this and figure out what's going on.  I will update this issue when it's resolved.

**Comment by thefiz** [comment]
This issue has something to do with the way Twitch hosts its clips. Twitch hosts videos in one of two ways.  Either:

https://clips-media-assets.twitch.tv/<clip_id>.mp4
https://clips-media-assets.twitch.tv/<broadcast_id>-offset-<time>.mp4

There is nothing I can see within the API that indicates a clip is either one or the other, the vast majority of clips are the first style, which is why the issue wasn't apparent to me until someone submitted it.

I am currently exploring how to resolve this issue.  I have received a few example clips already.  It appears that sometimes, the thumbnail image URL also has the offset text.  I was able to resolve about 50% of the non-loading clips by testing for that, and then applying that to the main clip.  However, some clips do not show an offset on the Thumbnail, but the URL for the clip itself is offset.  When this is the case, the API does not return the offset number AT ALL..

I am still exploring alternative methods to get the video.  We shall see what I come up with.

**Comment by captainswain** [comment]
Experiencing this issue as well. Trying to troubleshoot and see if there is any distinction!

**Comment by thefiz** [comment]
I have been given a solution using the Twitch Dev Forums.  However, it's not ideal, as the API it needs to use well is deprecated and will be removed in December.  I will implement it in the meantime however.

**Comment by captainswain** [comment]
Could you link me the article? I'd love to read it! I've been banging my head trying to fix this issue

- Swain

**Comment by thefiz** [comment]
Sure, here is [the forum post I made](https://discuss.dev.twitch.tv/t/clips-api-does-not-expose-video-url/15763/4)

**Comment by thefiz** [comment]
This is resolved in release v1.3

Please download the new binary from the releases page
